### ISSUE TITLE
EmptyFileError when reading fasta

### ISSUE THREAD

**Issue by lvzenglei** [Crispy13/GeneFuseRust#4]
```
(base) lvzenglei@computer-6:/nfs/disk7/user/lvzenglei/self_code/genefuse/newGeneFuseRust/GeneFuseRust-0.1.3$ /nfs/disk7/user/lvzenglei/self_code/genefuse/newGeneFuseRust/GeneFuseRust-0.1.3/target/release/genefuserust -t 20 -r /nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta -f /nfs/disk2/user/cuifenglei/Mybox/HTMLreport/Merge/genefuse/genefuse.hg19.csv -1 /nfs/disk7/519_sample/novo_sample/20240408/WKGS519G-240405-01/GS519G-240403-01F-f_S125_L001_R1_001.fastq.gz -2 /nfs/disk7/519_sample/novo_sample/20240408/WKGS519G-240405-01/GS519G-240403-01F-f_S125_L001_R2_001.fastq.gz -h /nfs/disk7/user/lvzenglei/self_code/genefuse/result/genefuse_rust/GS519G-240403-01_tumor_computer-6.log 

# /nfs/disk7/user/lvzenglei/self_code/genefuse/newGeneFuseRust/GeneFuseRust-0.1.3/target/release/genefuserust -t 20 -r /nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta -f /nfs/disk2/user/cuifenglei/Mybox/HTMLreport/Merge/genefuse/genefuse.hg19.csv -1 /nfs/disk7/519_sample/novo_sample/20240408/WKGS519G-240405-01/GS519G-240403-01F-f_S125_L001_R1_001.fastq.gz -2 /nfs/disk7/519_sample/novo_sample/20240408/WKGS519G-240405-01/GS519G-240403-01F-f_S125_L001_R2_001.fastq.gz -h /nfs/disk7/user/lvzenglei/self_code/genefuse/result/genefuse_rust/GS519G-240403-01_tumor_computer-6.log

thread 'main' panicked at src/genefuse.rs:37:15:
called `Result::unwrap()` on an `Err` value: EmptyFileError { cxt: "\"/nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta\"", loc: "src/core/fasta_reader.rs:82:17" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) lvzenglei@computer-6:/nfs/disk7/user/lvzenglei/self_code/genefuse/newGeneFuseRust/GeneFuseRust-0.1.3$ ls -lha /nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta
-rw-rwxr-- 1 2004 2004 3.0G Sep 25  2018 /nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta
```

**Comment by Crispy13** [comment]
It seems that other IO error occured, instead of empty file. 

I modified the code for that.

Would you clone main branch again and test it? 
I think It will show another error message then.

**Comment by lvzenglei** [comment]
It show another error message, but does not explain that. 
any idea to solve it ?
```
(base) lvzenglei@computer-6:/nfs/disk7/user/lvzenglei/self_code/genefuse/GeneFuseRust$ tail -f /nfs/disk7/user/lvzenglei/self_code/genefuse/result/genefuse_rust/GS519G-240327-01_genefuse_tumor_computer-6.log

# /nfs/disk7/user/lvzenglei/self_code/genefuse/GeneFuseRust/target/release/genefuse -t 20 -r /nfs/disk4/user/lishiqi/database/bed/ucsc.hg19.fasta -f /nfs/disk2/user/cuifenglei/Mybox/HTMLreport/Merge/genefuse/genefuse.hg19.csv -1 /nfs/disk7/519_sample/novo_sample/20240401/WKGS519G-240329-01/GS519G-240327-01F-f_S43_L001_R1_001.fastq.gz -2 /nfs/disk7/519_sample/novo_sample/20240401/WKGS519G-240329-01/GS519G-240327-01F-f_S43_L001_R2_001.fastq.gz -h /nfs/disk7/user/lvzenglei/self_code/genefuse/result/genefuse_rust/GS519G-240327-01_genefuse_tumor_computer-6.html

thread 'main' panicked at src/genefuse.rs:37:15:
called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
stack backtrace:
   0:     0x55d6120da729 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
   1:     0x55d61206d3c0 - core::fmt::write::he40921d4802ce2ac
   2:     0x55d6120acb1e - std::io::Write::write_fmt::h5de5a4e7037c9b20
   3:     0x55d6120dc14e - std::sys_common::backtrace::print::h11c067a88e3bdb22
   4:     0x55d6120db9f7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
   5:     0x55d6120dc9d1 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
   6:     0x55d6120dc4c0 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
   7:     0x55d6120dc416 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
   8:     0x55d6120dc403 - rust_begin_unwind
   9:     0x55d611f98914 - core::panicking::panic_fmt::ha6effc2775a0749c
  10:     0x55d611f98e72 - core::result::unwrap_failed::ha188096f98826595
  11:     0x55d612019965 - genefuse::main::hbcc5cbff96776797
  12:     0x55d611fb5013 - std::sys_common::backtrace::__rust_begin_short_backtrace::h163a5a77e3994d10
  13:     0x55d61201bb31 - main
  14:     0x7efda16aad90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15:     0x7efda16aae40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  16:     0x55d611faab75 - _start
  17:                0x0 - <unknown>
~
```

**Comment by Crispy13** [comment]
Does original genefuse work for the reference file?

If not, it is likely an io error, and you should test after moving the reference file into another device(not the nfs).

**Comment by lvzenglei** [comment]
Thanks for that
maybe I test too many times
&nbsp;and make my fasta file wrong, i just change the fasta,and have a try

---Original---
From: ***@***.***&gt;
Date: Fri, Apr 12, 2024 18:01 PM
To: ***@***.***&gt;;
Cc: "Zenglei ***@***.******@***.***&gt;;
Subject: Re: [Crispy13/GeneFuseRust] EmptyFileError when reading fasta (Issue#4)




 
Does original genefuse work for the reference file?
 
If not, it is likely an io error, and you should test after moving the reference file into another device(not the nfs).
